stages:
  - build
  - deploy
variables:
  IMAGE_NAME: "gligi/ark-server"

services:
  - docker:dind

image: docker:20

before_script:
  - apk add --no-cache w3m curl jq gawk grep bash
  - export ARK_TOOLS_VERSION="$(w3m -dump https://github.com/FezVrasta/ark-server-tools/tags | egrep -o "[0-9]+\.[0-9]+\.[0-9]+([a-z]+)?" | head -n 1)"
  - find . -name "*.sh" -print0 | xargs -0 -r -n1 bash -n
  - export TIMESTAMP="$(date +%s)"

build:docker:
  stage: build
  script:
    - >
      docker build
      --no-cache
      --pull
      --build-arg ARK_TOOLS_VERSION="${ARK_TOOLS_VERSION}"
      --tag "${IMAGE_NAME}:tools-${ARK_TOOLS_VERSION}"
      --tag "${IMAGE_NAME}:latest"
      --tag "${IMAGE_NAME}:latest-${TIMESTAMP}"
      --file "${CI_PROJECT_DIR}/Dockerfile"
      "${CI_PROJECT_DIR}"
  except:
    - master
  parallel:
    matrix:
      - IMAGE_NAME: [ "gligi/ark-server" ]

deploy:docker:
  stage: deploy
  script:
    - >
      docker build
      --no-cache
      --pull
      --build-arg ARK_TOOLS_VERSION="${ARK_TOOLS_VERSION}"
      --build-arg IMAGE_VERSION="${TIMESTAMP}"
      --tag "${IMAGE_NAME}:tools-${ARK_TOOLS_VERSION}"
      --tag "${IMAGE_NAME}:latest"
      --tag "${IMAGE_NAME}:latest-${TIMESTAMP}"
      --file "${CI_PROJECT_DIR}/Dockerfile"
      "${CI_PROJECT_DIR}"
    - >
      mkdir -p "${HOME}/.docker" &&
      mv "${DOCKER_CONFIG_JSON}" "${HOME}/.docker/config.json" &&
      chmod 0600 "${HOME}/.docker/config.json"
    - docker push "${IMAGE_NAME}:tools-${ARK_TOOLS_VERSION}"
    - docker push "${IMAGE_NAME}:latest"
    - docker push "${IMAGE_NAME}:latest-${TIMESTAMP}"
  only:
    - master
  parallel:
    matrix:
      - IMAGE_NAME: [ "gligi/ark-server" ]
